spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?erverTimezone=UTC;useUnicode=true&amp;characterEncoding=utf8&amp;characterSetResults=utf8
    username: root
    password: 248600
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
---
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.szi.springboot.*.entity
---
server:
  port: 8080
  error:
    path: /error
---
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    messages:
      encoding: UTF-8
    profiles:
      active: dev
  mvc:
    view:
      suffix: .html